### ISSUE TITLE
Product icons crashing vscode

### ISSUE THREAD

**Issue by leogurja** [piousdeer/vscode-adwaita#28]
Somehow, adding `"workbench.productIconTheme": "adwaita",` to my settings makes vscode instantly crash
It still crashes with `code --disable-extensions` and on `code-insiders` as well

running ONLY the recommended settings also crashes
```
{
  "window.titleBarStyle": "custom",
  "window.commandCenter": true,
  "window.autoDetectColorScheme": true,
  "workbench.preferredDarkColorTheme": "Adwaita Dark",
  "workbench.preferredLightColorTheme": "Adwaita Light",
  "workbench.productIconTheme": "adwaita",
  "editor.renderLineHighlight": "none",
  "workbench.iconTheme": null,
  "workbench.tree.indent": 12,
}
```

here are some details of the rest of my config:

I'm running the VSCode 1.95.3 RPM on Fedora Linux 41 (GNOME 47)

<details>
  <summary>settings.json</summary>

  ```
  {
    // vscode
    "breadcrumbs.enabled": false,
    "diffEditor.ignoreTrimWhitespace": false,
    "editor.cursorBlinking": "phase",
    "editor.cursorSmoothCaretAnimation": "on",
    "editor.cursorSurroundingLines": 12,
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.fontFamily": "FiraCode Nerd Font",
    "editor.fontLigatures": true,
    "editor.fontSize": 16,
    "editor.formatOnSave": true,
    "editor.linkedEditing": true,
    "editor.minimap.enabled": false,
    "editor.quickSuggestions": {
      "comments": "inline",
      "other": "inline",
      "strings": "inline"
    },
    "editor.renderLineHighlight": "gutter",
    "editor.renderWhitespace": "trailing",
    "editor.rulers": [120, 80],
    "editor.semanticHighlighting.enabled": true,
    "editor.tabSize": 2,
    "explorer.compactFolders": false,
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "explorer.confirmPasteNative": false,
    "explorer.fileNesting.enabled": true,
    "explorer.fileNesting.patterns": {
      "*.js": "${capture}.js.map, ${capture}.min.js, ${capture}.d.ts",
      "*.jsx": "${capture}.js",
      "*.ts": "${capture}.js",
      "*.tsx": "${capture}.ts",
      "eslint.config.*js": "prettier.config.*s, .prettierrc*",
      "next.config.*s": "next-env.d.ts",
      "package.json": "package-lock.json, yarn.lock, pnpm-lock.yaml, bun.lockb",
      "tailwind.config.*s": "postcss.config.*s",
      "tsconfig.json": "tsconfig.*.json"
    },
    "explorer.incrementalNaming": "smart",
    "extensions.ignoreRecommendations": true,
    "files.associations": {
      "**/requirements{/**,*}.{txt,in}": "pip-requirements",
      "*.css": "tailwindcss",
      "*.h": "c",
      ".sequelizerc": "javascript",
      "complex": "c"
    },
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "git.autofetch": true,
    "git.closeDiffOnOperation": true,
    "git.confirmSync": false,
    "git.mergeEditor": true,
    "git.openRepositoryInParentFolders": "always",
    "git.suggestSmartCommit": false,
    "git.terminalGitEditor": true,
    "git.untrackedChanges": "separate",
    "github.gitProtocol": "ssh",
    "scm.defaultViewMode": "tree",
    "search.defaultViewMode": "tree",
    "search.smartCase": true,
    "security.workspace.trust.untrustedFiles": "open",
    "terminal.integrated.cursorBlinking": true,
    "terminal.integrated.cursorStyle": "line",
    "terminal.integrated.cursorStyleInactive": "line",
    "terminal.integrated.defaultProfile.linux": "fish",
    "terminal.integrated.hideOnStartup": "whenEmpty",
    "terminal.integrated.showExitAlert": false,
    "terminal.integrated.smoothScrolling": true,
    "terminal.integrated.tabs.hideCondition": "never",
    "window.menuBarVisibility": "toggle",
    "window.titleBarStyle": "custom",
    "workbench.editor.customLabels.patterns": {
      "**/app/**/layout.tsx": "${dirname} - Layout",
      "**/app/**/page.tsx": "${dirname} - Page",
      "**/components/**/index.tsx": "${dirname} - Component"
    },
    "workbench.editor.limit.enabled": true,
    "workbench.iconTheme": "material-icon-theme",
    "workbench.layoutControl.enabled": true,
    "workbench.settings.openDefaultSettings": true,
    "workbench.sideBar.location": "right",
    // extensions
    "liveServer.settings.CustomBrowser": "chrome",
    "liveServer.settings.donotShowInfoMsg": true,
    "liveServer.settings.donotVerifyTags": true,
    "liveServer.settings.mount": [
      ["./lib", "/lib"],
      ["./src", "/src"]
    ],
    "stylelint.reportNeedlessDisables": true,
    "stylelint.validate": ["css", "less", "postcss", "sass", "scss"],
  
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "eslint.useFlatConfig": true,
    "eslint.validate": ["astro", "vue"],
    "[css][scss][sass][less]": {
      "editor.defaultFormatter": "stylelint.vscode-stylelint"
    },
    "html.format.maxPreserveNewLines": 1,
    "html.format.templating": true,
    "[html]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "java.compile.nullAnalysis.mode": "automatic",
    "java.completion.enabled": true,
    "java.configuration.detectJdksAtStart": true,
    "java.configuration.updateBuildConfiguration": "automatic",
    "java.edit.validateAllOpenBuffersOnChanges": true,
    "java.format.enabled": true,
    "java.import.gradle.enabled": true,
    "java.jdt.ls.lombokSupport.enabled": true,
    "java.server.launchMode": "Standard",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "redhat.telemetry.enabled": true,
    "rubyLsp.enableExperimentalFeatures": true,
    "rubyLsp.linters": ["rubocop"],
    "material-icon-theme.folders.theme": "specific",
    "workbench.colorTheme": "Adwaita Dark"
  }
  ```
</details>

<details>
  <summary>Log from <code>code --verbose</code></summary>
  I've cut some of the output (too long)

  ```
  Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
  [main 2024-11-26T13:24:29.062Z] CodeWindow: renderer process gone (reason: crashed, code: 159)
  Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
      at s.send (node:electron/js2c/browser_init:2:91810)
      at _.send (node:electron/js2c/browser_init:2:75243)
      at Cw.send (file:///usr/share/code/resources/app/out/main.js:36:23267)
      at df.p (file:///usr/share/code/resources/app/out/main.js:34:19014)
      at df.o (file:///usr/share/code/resources/app/out/main.js:34:18979)
      at df.m (file:///usr/share/code/resources/app/out/main.js:34:18841)
      at qo.value (file:///usr/share/code/resources/app/out/main.js:35:265)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:964)
      at file:///usr/share/code/resources/app/out/main.js:28:6435
      at qo.value (file:///usr/share/code/resources/app/out/main.js:28:5231)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.C (file:///usr/share/code/resources/app/out/main.js:33:816)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:1033)
      at qo.value (file:///usr/share/code/resources/app/out/main.js:28:5092)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:964)
      at App.T (file:///usr/share/code/resources/app/out/main.js:28:7343)
      at App.emit (node:events:531:35)
      at BrowserWindow.<anonymous> (node:electron/js2c/browser_init:2:12275)
      at BrowserWindow.emit (node:events:519:28)
  [7730:1126/102429.088136:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
  [main 2024-11-26T13:24:29.486Z] lifecycle (main): phase changed (value: 4)
  [7686:1126/102431.420716:ERROR:browser_main_loop.cc(283)] GLib-GObject: ../gobject/gsignal.c:2684: instance '0x22dc02e0f580' has no handler with id '3105'
  [main 2024-11-26T13:24:31.423Z] IPC Object URL: Removed channel vscode:1aac38c0-717c-47a0-a141-153bce009759.
  Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
      at s.send (node:electron/js2c/browser_init:2:91810)
      at _.send (node:electron/js2c/browser_init:2:75243)
      at Cw.send (file:///usr/share/code/resources/app/out/main.js:36:23267)
      at df.p (file:///usr/share/code/resources/app/out/main.js:34:19014)
      at df.o (file:///usr/share/code/resources/app/out/main.js:34:18979)
      at df.m (file:///usr/share/code/resources/app/out/main.js:34:18841)
      at qo.value (file:///usr/share/code/resources/app/out/main.js:35:265)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:964)
      at qo.value (file:///usr/share/code/resources/app/out/main.js:28:5092)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:964)
      at qo.value (file:///usr/share/code/resources/app/out/main.js:28:4908)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.C (file:///usr/share/code/resources/app/out/main.js:33:816)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:1033)
      at v4.deregisterLogger (file:///usr/share/code/resources/app/out/main.js:38:18324)
      at v4.deregisterLogger (file:///usr/share/code/resources/app/out/main.js:53:30561)
      at v4.deregisterLoggers (file:///usr/share/code/resources/app/out/main.js:53:31189)
      at ac.dispose (file:///usr/share/code/resources/app/out/main.js:72:2238)
      at qo.value (file:///usr/share/code/resources/app/out/main.js:71:46700)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:964)
      at BrowserWindow.T (file:///usr/share/code/resources/app/out/main.js:28:7343)
      at BrowserWindow.emit (node:events:531:35)
      at ac.zb (file:///usr/share/code/resources/app/out/main.js:71:55886)
      at ac.yb (file:///usr/share/code/resources/app/out/main.js:71:55370)
      at MessagePortMain.postMessage (node:electron/js2c/browser_init:2:105577)
      at Object.postMessage (file:///usr/share/code/resources/app/out/main.js:36:24706)
      at Lw.send (file:///usr/share/code/resources/app/out/main.js:36:24278)
      at df.p (file:///usr/share/code/resources/app/out/main.js:34:19014)
      at df.o (file:///usr/share/code/resources/app/out/main.js:34:18979)
      at df.m (file:///usr/share/code/resources/app/out/main.js:34:18841)
      at qo.value (file:///usr/share/code/resources/app/out/main.js:35:265)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.C (file:///usr/share/code/resources/app/out/main.js:33:816)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:1033)
      at file:///usr/share/code/resources/app/out/main.js:28:6435
      at qo.value (file:///usr/share/code/resources/app/out/main.js:28:5231)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.C (file:///usr/share/code/resources/app/out/main.js:33:816)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:1033)
      at qo.value (file:///usr/share/code/resources/app/out/main.js:28:5092)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:964)
      at App.T (file:///usr/share/code/resources/app/out/main.js:28:7343)
      at App.emit (node:events:531:35)
      at BrowserWindow.<anonymous> (node:electron/js2c/browser_init:2:12336)
      at BrowserWindow.emit (node:events:531:35)
  Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
      at s.send (node:electron/js2c/browser_init:2:91810)
      at _.send (node:electron/js2c/browser_init:2:75243)
      at Cw.send (file:///usr/share/code/resources/app/out/main.js:36:23267)
      at df.p (file:///usr/share/code/resources/app/out/main.js:34:19014)
      at df.o (file:///usr/share/code/resources/app/out/main.js:34:18979)
      at df.m (file:///usr/share/code/resources/app/out/main.js:34:18841)
      at qo.value (file:///usr/share/code/resources/app/out/main.js:35:265)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:964)
      at qo.value (file:///usr/share/code/resources/app/out/main.js:28:5092)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:964)
      at qo.value (file:///usr/share/code/resources/app/out/main.js:28:4908)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.C (file:///usr/share/code/resources/app/out/main.js:33:816)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:1033)
      at v4.deregisterLogger (file:///usr/share/code/resources/app/out/main.js:38:18324)
      at v4.deregisterLogger (file:///usr/share/code/resources/app/out/main.js:53:30561)
      at v4.deregisterLoggers (file:///usr/share/code/resources/app/out/main.js:53:31189)
      at ac.dispose (file:///usr/share/code/resources/app/out/main.js:72:2238)
      at qo.value (file:///usr/share/code/resources/app/out/main.js:71:46700)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:964)
      at BrowserWindow.T (file:///usr/share/code/resources/app/out/main.js:28:7343)
      at BrowserWindow.emit (node:events:531:35)
      at ac.zb (file:///usr/share/code/resources/app/out/main.js:71:55886)
      at ac.yb (file:///usr/share/code/resources/app/out/main.js:71:55370)
      at MessagePortMain.postMessage (node:electron/js2c/browser_init:2:105577)
      at Object.postMessage (file:///usr/share/code/resources/app/out/main.js:36:24706)
      at Lw.send (file:///usr/share/code/resources/app/out/main.js:36:24278)
      at df.p (file:///usr/share/code/resources/app/out/main.js:34:19014)
      at df.o (file:///usr/share/code/resources/app/out/main.js:34:18979)
      at df.m (file:///usr/share/code/resources/app/out/main.js:34:18841)
      at qo.value (file:///usr/share/code/resources/app/out/main.js:35:265)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.C (file:///usr/share/code/resources/app/out/main.js:33:816)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:1033)
      at file:///usr/share/code/resources/app/out/main.js:28:6435
      at qo.value (file:///usr/share/code/resources/app/out/main.js:28:5231)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.C (file:///usr/share/code/resources/app/out/main.js:33:816)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:1033)
      at qo.value (file:///usr/share/code/resources/app/out/main.js:28:5092)
      at P.B (file:///usr/share/code/resources/app/out/main.js:33:746)
      at P.fire (file:///usr/share/code/resources/app/out/main.js:33:964)
      at App.T (file:///usr/share/code/resources/app/out/main.js:28:7343)
      at App.emit (node:events:531:35)
      at BrowserWindow.<anonymous> (node:electron/js2c/browser_init:2:12336)
      at BrowserWindow.emit (node:events:531:35)
  [main 2024-11-26T13:24:31.424Z] Lifecycle#window.on('closed') - window ID 1
  [main 2024-11-26T13:24:31.424Z] Lifecycle#onWillShutdown.fire()
  [main 2024-11-26T13:24:31.425Z] Lifecycle#onWillShutdown - begin 'instanceLockfile'
  [main 2024-11-26T13:24:31.425Z] storageMainService#onWillShutdown()
  [main 2024-11-26T13:24:31.425Z] Lifecycle#onWillShutdown - begin 'applicationStorage'
  [main 2024-11-26T13:24:31.425Z] Lifecycle#onWillShutdown - begin 'workspaceStorage'
  [main 2024-11-26T13:24:31.426Z] Lifecycle#onWillShutdown - begin 'extHostStarter'
  [main 2024-11-26T13:24:31.426Z] [UtilityProcess id: 1, type: fileWatcher, pid: 7818]: attempting to kill the process...
  [main 2024-11-26T13:24:31.426Z] [UtilityProcess id: 1, type: fileWatcher, pid: 7818]: successfully killed the process
  [main 2024-11-26T13:24:31.426Z] Lifecycle#app.on(window-all-closed)
  [main 2024-11-26T13:24:31.426Z] Lifecycle#app.on(before-quit)
  [main 2024-11-26T13:24:31.426Z] Lifecycle#onBeforeShutdown.fire()
  [main 2024-11-26T13:24:31.426Z] [WindowsStateHandler] onBeforeShutdown {
    lastActiveWindow: undefined,
    lastPluginDevelopmentHostWindow: undefined,
    openedWindows: []
  }
  [main 2024-11-26T13:24:31.426Z] Lifecycle#app.on(will-quit) - begin
  [main 2024-11-26T13:24:31.426Z] Lifecycle#onWillShutdown - end 'extHostStarter'
  [main 2024-11-26T13:24:31.427Z] [uncaught exception in main]: TypeError: Object has been destroyed
  [main 2024-11-26T13:24:31.427Z] TypeError: Object has been destroyed
      at file:///usr/share/code/resources/app/out/main.js:50:4311
      at App.T (file:///usr/share/code/resources/app/out/main.js:28:7348)
      at App.emit (node:events:531:35)
      at BrowserWindow.<anonymous> (node:electron/js2c/browser_init:2:12336)
      at BrowserWindow.emit (node:events:531:35)
  [main 2024-11-26T13:24:31.428Z] Lifecycle#onWillShutdown - end 'instanceLockfile'
  [main 2024-11-26T13:24:31.429Z] [File Watcher (node.js)] Request to stop watching: /home/gurja/.config/Code/User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>),/home/gurja/.config/Code/User/settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>)
  [main 2024-11-26T13:24:31.429Z] [File Watcher (node.js)] stopping file watcher (/home/gurja/.config/Code/User (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>))
  [main 2024-11-26T13:24:31.429Z] [File Watcher (node.js)] stopping file watcher (/home/gurja/.config/Code/User/settings.json (excludes: <none>, includes: <all>, filter: <none>, correlationId: <none>))
  [main 2024-11-26T13:24:31.429Z] StorageMainService: closed workspace storage (1732627467069)
  [main 2024-11-26T13:24:31.429Z] Lifecycle#onWillShutdown - end 'workspaceStorage'
  [main 2024-11-26T13:24:31.430Z] StorageMainService: closed application storage
  [main 2024-11-26T13:24:31.430Z] Lifecycle#onWillShutdown - end 'applicationStorage'
  [main 2024-11-26T13:24:31.433Z] [UtilityProcess id: 1, type: fileWatcher, pid: 7818]: received exit event with code 0
  [main 2024-11-26T13:24:31.434Z] [UtilityProcessWorker]: terminated normally with code 0, signal: unknown
  [main 2024-11-26T13:24:31.434Z] Lifecycle#app.on(will-quit) - after fireOnWillShutdown
  [main 2024-11-26T13:24:31.434Z] Lifecycle#app.on(will-quit) - calling app.quit()
  ```

**Comment by piousdeer** [comment]
I can't reproduce this on VS Code 1.95.2 on NixOS 24.11, GNOME 47, Wayland, Nvidia. Will wait for further reports.

**Comment by leogurja** [comment]
found out `code --disable-extensions` actually fixes it.

here are my other extensions:
```
astro-build.astro-vscode
bradlc.vscode-tailwindcss
davidanson.vscode-markdownlint
dbaeumer.vscode-eslint
esbenp.prettier-vscode
fwcd.kotlin
golang.go
koichisasada.vscode-rdbg
ms-python.debugpy
ms-python.python
ms-vscode.cpptools
naumovs.color-highlight
piousdeer.adwaita-theme
pkief.material-icon-theme
prisma.prisma
redhat.java
ritwickdey.liveserver
shopify.ruby-extensions-pack
shopify.ruby-lsp
sorbet.sorbet-vscode-extension
stylelint.vscode-stylelint
twxs.cmake
unifiedjs.vscode-mdx
visualstudioexptteam.vscodeintellicode
vscjava.vscode-lombok
vue.volar
wix.vscode-import-cost
zignd.html-css-class-completion
```

**Comment by leogurja** [comment]
It's most likely a problem with vscode itself. I'm closing this issue but I will keep this thread updated if something changes.

If anyone has this same problem please comment
Removing `"workbench.productIconTheme": "adwaita"` from settings fixes the crash

**Comment by nonvenomous** [comment]
I'm experiencing the same kind of crash right after starting vscode.
I'm also on VSCode 1.95.3 RPM on Fedora Linux 41 (GNOME 47.1)

After some tedious work I was able to narrow it down to the adwaita extension.  Disabling the extension or only removing the mentioned setting property by @gurgelio also stops the crashing.
I can reproduce the crash even with no other extensions installed.

On VSCode 1.95.3 flatpak I'm unable to reproduce it.

**Comment by vorburger** [comment]
FTR This is now reported on VSC as https://github.com/microsoft/vscode/issues/237058 (see #29).
